import math


SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
TITLE = "FPS Game"

FOV = 60
NUM_RAYS = SCREEN_WIDTH
MAX_DEPTH = 20
HALF_FOV = FOV / 2
DELTA_ANGLE = FOV / NUM_RAYS
SCREEN_DIST = SCREEN_WIDTH / (2 * math.tan(math.radians(HALF_FOV)))

